use_frameworks!

target 'AJAppEventSwift_Example' do
  pod 'AJAppEventSwift', :path => '../'

#  pod 'AJKitSwift',
#  :subspecs => ['Foundation', 'UIKit'],
#  :path => '../../AJKitSwift'
  pod 'AJKitSwift'
  
end
