use_frameworks!

target 'AJAppEventSwift_Example' do
  pod 'AJAppEventSwift', :path => '../'

  pod 'AJKitSwift',
  :subspecs => ['Foundation', 'UIKit', 'Runtime', 'Algorithm'],
  :path => '../../AJKitSwift'
  
end
